# INTENT RECOGNITION WORDS

GENERAL_SEARCH_KEYWORDS = [
    "ligar reconhecimento de objetos",
    "ligar reconhecedor de objetos",
    "ligar reconhecedor de objeto",
    "ligue reconhecimento de objetos",
    "ligue reconhecedor de objetos",
    "ligue reconhecedor de objeto",
    "ativar reconhecimento de objetos",
    "ativar reconhecedor de objetos",
    "ativar reconhecedor de objeto",
    "ative reconhecimento de objetos",
    "ative reconhecedor de objetos",
    "ative reconhecedor de objeto",
    "iniciar reconhecimento de objetos",
    "iniciar reconhecedor de objetos",
    "inicie reconhecimento de objetos",
    "inicie reconhecedor de objetos",
    "habilitar reconhecimento de objetos",
    "habilitar reconhecedor de objetos",
    "habilite reconhecimento de objetos",
    "habilite reconhecedor de objetos",
    "começar reconhecimento de objetos",
    "comece reconhecimento de objetos",
    "usar reconhecimento de objetos",
    "usar reconhecedor de objetos",
    "usar detector de objetos",
    "ativar detector de objetos",
    "ative detector de objetos",
    "ligar detector de objetos",
    "ligue detector de objetos",
    "iniciar detector de objetos",
    "inicie detector de objetos",
    "habilitar detector de objetos",
    "habilite detector de objetos",
    "abrir reconhecimento de objetos",
    "abra reconhecimento de objetos",
    "executar reconhecimento de objetos",
    "executar detector de objetos",
    "rodar reconhecimento de objetos",
    "rodar detector de objetos",
    "quero reconhecer objetos",
    "quero detectar objetos",
    "identificar objetos",
    "identifique objetos",
    "reconhecer objetos",
    "detectar objetos",
    "detecção de objetos",
    "modo reconhecimento de objetos",
    "modo detector de objetos",
]

NONE_KEYWORDS = [
    "desligar reconhecimento de objetos",
    "desligar reconhecedor de objetos",
    "desligar reconhecedor de objeto",
    "desligue reconhecimento de objetos",
    "desligue reconhecedor de objetos",
    "desligue reconhecedor de objeto",
    "desativar reconhecimento de objetos",
    "desativar reconhecedor de objetos",
    "desativar reconhecedor de objeto",
    "desative reconhecimento de objetos",
    "desative reconhecedor de objetos",
    "desative reconhecedor de objeto",
    "parar reconhecimento de objetos",
    "parar reconhecedor de objetos",
    "pare reconhecimento de objetos",
    "pare reconhecedor de objetos",
    "encerrar reconhecimento de objetos",
    "encerrar reconhecedor de objetos",
    "encerre reconhecimento de objetos",
    "encerre reconhecedor de objetos",
    "fechar reconhecimento de objetos",
    "feche reconhecimento de objetos",
    "desabilitar reconhecimento de objetos",
    "desabilitar reconhecedor de objetos",
    "desabilite reconhecimento de objetos",
    "desabilite reconhecedor de objetos",
    "desligar detector de objetos",
    "desligue detector de objetos",
    "desativar detector de objetos",
    "desative detector de objetos",
    "parar detector de objetos",
    "pare detector de objetos",
    "encerrar detector de objetos",
    "encerre detector de objetos",
    "fechar detector de objetos",
    "feche detector de objetos",
    "parar detecção de objetos",
    "pare detecção de objetos",
    "encerrar detecção de objetos",
    "desativar detecção de objetos",
    "desative detecção de objetos",
    "sair do reconhecimento de objetos",
    "sair do detector de objetos",
    "sair da detecção de objetos",
    "quero parar de reconhecer objetos",
    "quero parar de detectar objetos",
    "parar reconhecimento",
    "desligar reconhecimento",
    "desativar reconhecimento",
    "modo normal",
    "voltar ao modo normal",
    "sair do modo reconhecimento de objetos",
    "desligar modo reconhecimento de objetos",
    "desativar modo reconhecimento de objetos",
]